### ISSUE TITLE
Реализовать базовую логику работы с сущностями

### ISSUE THREAD

**Issue by FrediKats** [InRedikaWB/ScheduleAggregator#19]
Для добавленных сущностей было бы неплохо реализовать репозитории и сервисы. Минимум - методы получения всех и добавления новых.

**Comment by VitalDikov** [comment]
Лучше держать все сущности в одном репозитории и создать методы типа FindTeacher, FindLesson etc. Или для каждой сущности отдельный репозиторий и сервис?

**Comment by FrediKats** [comment]
Кмк, проще всего сделать дженерик репозиторий, там код всегда однотипный. Например, как тут - https://github.com/kysect/iwentys/blob/master/Source/Shared/Iwentys.Common/Databases/IGenericRepository.cs (возможно только там IQueryble проще пока убрать, заменить на IEnumerable)

А вот сервисы уже отдельные, для каждой сущности.
cc: @s4xack

**Comment by s4xack** [comment]
@VitalDikov  
> Для добавленных сущностей было бы неплохо реализовать репозитории и **сервисы**

Пока сделаны ток репозитории, так что ишуя закрыта ток наполовину

**Comment by FrediKats** [comment]
Так-то можно сразу накинуть пару тестов. На дым, чтобы проверить, что можно дб контекст развернуть и что-то добавить
